---
- name: Provisioning server
  hosts: all
  become: yes
  tasks:
    - name: Install ntp agent on centos
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - chrony
        - wget
        - git
        - unzip
        - zip

    - name: Install ntp agent on ubuntu
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu" 
      loop:
        - ntp
        - wget
        - git
        - unzip
        - zip


    - name: Start Service on centOS
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"
    
    - name: Start Service on ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"


    - name: BannweFi
      copy:
        content: '# This server is managed by ansible. No Manual changes please!'
        dest: /etc/motd
    
    - name: Deploy ntp agent conf on centos
      template:
        src: templates/ntpconf_centos
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "CentOS"
      notify:
        - Restart Service on centOS

    - name: Deploy ntp agent conf on ubuntu
      template:
        src: templates/ntpconf_ubuntu
        dest: /etc/ntpsec/ntp.conf
        backup: yes
      when: ansible_distribution == "Ubuntu"      
      notify:
        - Restart Service on ubuntu

  handlers:
    - name: Restart Service on centOS
      service:
        name: chronyd
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Restart Service on ubuntu
      service:
        name: ntp
        state: restarted
        enabled: yes
      when: ansible_distribution == "Ubuntu"
    
